# Generated by Django 4.2.23 on 2025-07-31 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('perfil', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_comercial',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente asociado a este proyecto', limit_choices_to={'tipo_usuario': 'cliente'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='desarrollador',
            field=models.ForeignKey(blank=True, help_text='Desarrollador asignado a este proyecto', limit_choices_to={'tipo_usuario': 'desarrollador'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_desarrollador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado de este proyecto', max_length=15),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='invitacion_email_destinatario',
            field=models.EmailField(blank=True, help_text='Email del destinatario de la invitación', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='invitacion_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado de la invitación para este proyecto', max_length=15),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='invitacion_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha de la invitación para este proyecto', null=True),
        ),
    ]
