# Generated by Django 4.2.23 on 2025-08-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_desarrollador_rename_nombre_comercial_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='desarrollador_asociado',
            field=models.ForeignKey(blank=True, help_text='Desarrollador asociado a este usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.desarrollador'),
        ),
    ]
