# Generated by Django 4.2.23 on 2025-07-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=20)),
                ('contacto_nombre', models.CharField(blank=True, max_length=15, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('total_facturacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
